# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHub\LoginUI\Dialog_Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_Login(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(492, 672)
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.label_login = QtWidgets.QLabel(Dialog)
        self.label_login.setGeometry(QtCore.QRect(180, 80, 121, 51))
        self.label_login.setStyleSheet("font: 28pt \"Arial\";\n"
"color: rgb(226, 226, 226);")
        self.label_login.setObjectName("label_login")
        self.label_Email = QtWidgets.QLabel(Dialog)
        self.label_Email.setGeometry(QtCore.QRect(40, 230, 71, 41))
        self.label_Email.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(255, 0, 127);")
        self.label_Email.setObjectName("label_Email")
        self.lineEdit_email = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_email.setGeometry(QtCore.QRect(180, 220, 281, 51))
        self.lineEdit_email.setStyleSheet("font: 12pt \"等线\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.label_Password = QtWidgets.QLabel(Dialog)
        self.label_Password.setGeometry(QtCore.QRect(40, 360, 131, 41))
        self.label_Password.setStyleSheet("font: 16pt \"Arial\";\n"
"color: rgb(255, 0, 127);")
        self.label_Password.setObjectName("label_Password")
        self.lineEdit_password = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_password.setGeometry(QtCore.QRect(180, 350, 281, 51))
        self.lineEdit_password.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"等线\";")
        self.lineEdit_password.setObjectName("lineEdit_password")
        self.pushButton_Login = QtWidgets.QPushButton(Dialog)
        self.pushButton_Login.setGeometry(QtCore.QRect(302, 500, 161, 41))
        self.pushButton_Login.setStyleSheet("background-color: rgb(185, 185, 185);\n"
"color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";")
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.label_Donot = QtWidgets.QLabel(Dialog)
        self.label_Donot.setGeometry(QtCore.QRect(40, 445, 231, 21))
        self.label_Donot.setStyleSheet("font: 12pt \"Arial\";\n"
"color: rgb(255, 255, 255);")
        self.label_Donot.setObjectName("label_Donot")
        self.pushButton_CreateAcc = QtWidgets.QPushButton(Dialog)
        self.pushButton_CreateAcc.setGeometry(QtCore.QRect(300, 440, 161, 28))
        self.pushButton_CreateAcc.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(54, 54, 54);\n"
"font: 12pt \"Arial\";")
        self.pushButton_CreateAcc.setObjectName("pushButton_CreateAcc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_login.setText(_translate("Dialog", "Login"))
        self.label_Email.setText(_translate("Dialog", "Email"))
        self.label_Password.setText(_translate("Dialog", "Password"))
        self.pushButton_Login.setText(_translate("Dialog", "Login"))
        self.label_Donot.setText(_translate("Dialog", "Don\'t have an account?"))
        self.pushButton_CreateAcc.setText(_translate("Dialog", "Create Account"))
